# Configuration file for 14-90-STANDARD-PARTS-CATALOG
# This file is intentionally minimal to allow inheritance from domain-level configuration

ata_chapter: 14
sub_zone: 14-90-STANDARD-PARTS-CATALOG
domain: AAA
project: AMPEL360-AIR-T
