# Configuration file for 14-60-CLAMPS-CLIPS-TIES
# This file is intentionally minimal to allow inheritance from domain-level configuration

ata_chapter: 14
sub_zone: 14-60-CLAMPS-CLIPS-TIES
domain: AAA
project: AMPEL360-AIR-MANNED
