# Configuration file for 14-70-SAFETY-WIRE-COTTER
# This file is intentionally minimal to allow inheritance from domain-level configuration

ata_chapter: 14
sub_zone: 14-70-SAFETY-WIRE-COTTER
domain: AAA
project: AMPEL360-AIR-MANNED
