# Configuration file for 14-40-BOLTS-NUTS-WASHERS
# This file is intentionally minimal to allow inheritance from domain-level configuration

ata_chapter: 14
sub_zone: 14-40-BOLTS-NUTS-WASHERS
domain: AAA
project: AMPEL360-AIR-T
