# Configuration file for 14-20-FASTENERS-GENERAL
# This file is intentionally minimal to allow inheritance from domain-level configuration

ata_chapter: 14
sub_zone: 14-20-FASTENERS-GENERAL
domain: AAA
project: AMPEL360-AIR-T
